name: Release

on:
  release:
    types: released

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - run: |
          pip install build
      - run: |
          python -m build
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
      - uses: svenstaro/upload-release-action@2.3.0
        with:
          file: dist/*
          file_glob: true

  qgis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      # use extra pip install . to do a non-editable install,
      # so that .dist-info will go the package instead of .egg-info
      - run: |
          pip install -r requirements.txt --no-deps --only-binary=:all:
          pip install . --no-deps
      - run: |
          qgis-plugin-dev-tools build
      # no qgis repo publish yet for the dummy plugin gui
      # - run: |
      #     qgis-plugin-dev-tools publish dist/*.zip
      #   env:
      #     QPDT_PUBLISH_USERNAME: ${{ secrets.QGIS_REPO_USERNAME }}
      #     QPDT_PUBLISH_PASSWORD: ${{ secrets.QGIS_REPO_PASSWORD }}
      - uses: svenstaro/upload-release-action@2.3.0
        with:
          file: dist/*
          file_glob: true
